// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'aqua',
    {
      type: 'category',
      label: '西洋棋',
      items: [{type: 'autogenerated', dirName: 'chess'}],
    },
    {
      type: 'category',
      label: '音樂',
      items: [{type: 'autogenerated', dirName: 'music'}],
    },
    {
      type: 'category',
      label: '魔術方塊',
      items: [{type: 'autogenerated', dirName: 'rubiks_cube'}],
    },
    'keyboard',
    'concert',
    'draw',
    'motorcycle',
  ],
  rankingSidebar: [
    {type: 'autogenerated', dirName: 'ranking'},
  ],
};

export default sidebars;
